package algonquin.cst2335.finalproject.data;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a flight entity with its details such as destination, IATA code arrival, terminal, gate, and delay.
 * This class is used in conjunction with Room database to store flight information.
 *
 * @author Jato Ulrich Guiffo Kengne
 */
@Entity
public class Flight {
    // Fields representing flight details
    /**
     * Primary key for the Flight table, automatically generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private long id;

    /**
     * The destination of the flight.
     */
    @ColumnInfo(name = "Destination")
    private String destination;

    /**
     * The IATA code for the arrival airport of the flight.
     */
    @ColumnInfo(name = "IataCodeArrival")
    private String iataCodeArrival;

    /**
     * The terminal number of the flight.
     */
    @ColumnInfo(name = "Terminal")
    private String terminal;

    /**
     * The gate number of the flight.
     */
    @ColumnInfo(name = "Gate")
    private String gate;

    /**
     * The delay information of the flight.
     */
    @ColumnInfo(name = "Delay")
    private String delay;

    /**
     * Default constructor for the Flight class.
     * This is required by Room database to create Flight instances from database queries.


     /**
     * Default constructor for the Flight class.
     * This is required by Room database to create Flight instances from database queries.
     */
    public Flight() {}

    /**
     * Constructor for the Flight class.
     * @param destination The destination of the flight.
     * @param iataCodeArrival The IATA code for the arrival airport.
     * @param terminal The terminal number of the flight.
     * @param gate The gate number of the flight.
     * @param delay The delay information of the flight.
     */
    public Flight(String destination, String iataCodeArrival, String terminal, String gate, String delay) {
        this.destination = destination;
        this.iataCodeArrival = iataCodeArrival;
        this.terminal = terminal;
        this.gate = gate;
        this.delay = delay;
    }

    // Getter and Setter methods for all fields

    /**
     * Get the ID of the flight.
     * @return The ID of the flight.
     */
    public long getId() {
        return id;
    }

    /**
     * Set the ID of the flight.
     * @param id The ID to set for the flight.
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Get the destination of the flight.
     * @return The destination of the flight.
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Set the destination of the flight.
     * @param destination The destination to set for the flight.
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * Get the IATA code for the arrival airport of the flight.
     * @return The IATA code for the arrival airport.
     */
    public String getIataCodeArrival() {
        return iataCodeArrival;
    }

    /**
     * Set the IATA code for the arrival airport of the flight.
     * @param iataCodeArrival The IATA code to set for the arrival airport.
     */
    public void setIataCodeArrival(String iataCodeArrival) {
        this.iataCodeArrival = iataCodeArrival;
    }

    /**
     * Get the terminal number of the flight.
     * @return The terminal number of the flight.
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * Set the terminal number of the flight.
     * @param terminal The terminal number to set for the flight.
     */
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    /**
     * Get the gate number of the flight.
     * @return The gate number of the flight.
     */
    public String getGate() {
        return gate;
    }

    /**
     * Set the gate number of the flight.
     * @param gate The gate number to set for the flight.
     */
    public void setGate(String gate) {
        this.gate = gate;
    }

    /**
     * Get the delay information of the flight.
     * @return The delay information of the flight.
     */
    public String getDelay() {
        return delay;
    }

    /**
     * Set the delay information of the flight.
     * @param delay The delay information to set for the flight.
     */
    public void setDelay(String delay) {
        this.delay = delay;
    }
}
