package algonquin.cst2335.finalproject.Currency;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
/**
 * CurrencyObject is a model class representing a currency conversion object.
 * It contains the details of a currency conversion, such as the currencies being converted,
 * the amount in the 'from' currency, and the converted amount in the 'to' currency.
 * The class is annotated with @Entity to specify that it represents an entity in the Room database.
 */
@Entity
public class CurrencyObject {

    /**
     * The 'from' currency in the currency conversion.
     */
    @ColumnInfo(name = "convertfrom")
    String converto;

    /**
     * The 'to' currency in the currency conversion.
     */
    @ColumnInfo(name = "convertto")
    String convertfrom ;

    /**
     * The amount in the 'from' currency.
     */
    @ColumnInfo(name = "cfom")
    String cfrom;

    /**
     * The converted amount in the 'to' currency.
     */
    @ColumnInfo(name = "too")
    String too;

    /**
     * The primary key auto-generated by the Room database.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int id;

    /**
     * Default constructor for the CurrencyObject class.
     */
    public CurrencyObject() {
    }

    /**
     * Constructor for the CurrencyObject class to set the currency conversion details.
     *
     * @param t  The 'to' currency in the currency conversion.
     * @param f  The 'from' currency in the currency conversion.
     * @param af The amount in the 'from' currency.
     * @param at The converted amount in the 'to' currency.
     */
    public CurrencyObject(String t, String f, String af, String at) {
        this.converto = t;
        this.convertfrom = f;
        this.cfrom = af;
        this.too = at;
    }

    /**
     * Gets the 'to' currency in the currency conversion.
     *
     * @return The 'to' currency.
     */
    public String getConverto() {
        return converto;
    }

    /**
     * Gets the 'from' currency in the currency conversion.
     *
     * @return The 'from' currency.
     */
    public String getConvertfrom() {
        return convertfrom;
    }

    /**
     * Gets the amount in the 'from' currency.
     *
     * @return The amount in the 'from' currency.
     */
    public String getCfrom() {
        return cfrom;
    }

    /**
     * Gets the converted amount in the 'to' currency.
     *
     * @return The converted amount in the 'to' currency.
     */
    public String getToo() {
        return too;
    }

    /**
     * Gets the primary key ID of the currency conversion in the Room database.
     *
     * @return The primary key ID.
     */
    public int getId() {
        return id;
    }
}
