/**
 * Represents an entity class for storing image details in the database.
 */
package algonquin.cst2335.finalproject.bearData;

import android.graphics.Bitmap;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
import androidx.room.TypeConverters;

@Entity
@TypeConverters(BitmapTypeConverter.class)
public class ImageEntity {

    /**
     * The primary key of the image entity, auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private long id;

    /**
     * The height of the image in pixels.
     */
    @ColumnInfo(name = "Height")
    private int height;

    /**
     * The width of the image in pixels.
     */
    @ColumnInfo(name = "width")
    private int weight;

    /**
     * The image stored as a Bitmap object.
     */
    @ColumnInfo(name = "Image")
    private Bitmap image;

    /**
     * Default constructor for the ImageEntity class.
     */
    public ImageEntity() {}

    /**
     * Constructor for creating an ImageEntity object with specified details.
     *
     * @param height The height of the image in pixels.
     * @param weight The width of the image in pixels.
     * @param image The image as a Bitmap object.
     */
    public ImageEntity(int height, int weight, Bitmap image) {
        this.height = height;
        this.weight = weight;
        this.image = image;
    }

    /**
     * Retrieves the ID of the image entity.
     *
     * @return The ID of the image entity.
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the ID of the image entity.
     *
     * @param id The ID to set for the image entity.
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Retrieves the height of the image.
     *
     * @return The height of the image in pixels.
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the height of the image.
     *
     * @param height The height to set for the image.
     */
    public void setHeight(int height) {
        this.height = height;
    }

    /**
     * Retrieves the width of the image.
     *
     * @return The width of the image in pixels.
     */
    public int getWeight() {
        return weight;
    }

    /**
     * Sets the width of the image.
     *
     * @param weight The width to set for the image.
     */
    public void setWeight(int weight) {
        this.weight = weight;
    }

    /**
     * Retrieves the image as a Bitmap object.
     *
     * @return The image as a Bitmap object.
     */
    public Bitmap getImage() {
        return image;
    }

    /**
     * Sets the image as a Bitmap object.
     *
     * @param image The image to set as a Bitmap object.
     */
    public void setImage(Bitmap image) {
        this.image = image;
    }
}
